#!/usr/bin/env bash
#
# reset-dev-data.sh — wipe the DEV database and re-seed the standard dataset.
#
# Everything in the database is destroyed EXCEPT the Cosmetri token pair
# (`cosmetri_connection`), which is dumped before the wipe and restored after.
# That row is deliberately special-cased: it can only be recreated by pasting an
# access/refresh token obtained out-of-band from the real Cosmetri account
# (Cosmetri has no app-registration/OAuth client flow), so losing it costs real
# effort — everything else is generated by the seeder from config.
#
# What you get afterwards (see apps/api/prisma/seed.ts):
#   - 1 demo project  MBC-2026-001 / MBB-BALM-50, full scaffold from config
#   - 13 review owners assigned to it (Chris, Tuan, George, Sankar, …)
#   - 30 users (17 one-per-SSO-role demo accounts + the 13 review owners),
#     every one of them with a role
#   - 17 roles, 17 permissions, the demo-parity permission grid (awaiting F6)
#   - rule config: safety triggers (C1) + ingredient watch-lists (C3 stand-in)
#
# Usage:
#   ./reset-dev-data.sh              # ask for confirmation, then reset
#   ./reset-dev-data.sh --yes        # no prompt (scripted / CI use)
#   ./reset-dev-data.sh --keep-users # keep real SSO users too, not just tokens
#   ./reset-dev-data.sh --help
#
# Real Microsoft-365 users ARE deleted by default: SSO recreates them on the
# next sign-in, and with AUTH_AUTO_ADMIN_ROLE=true they get the admin role back
# automatically. Use --keep-users if you would rather not re-login.
set -euo pipefail

cd "$(dirname "$0")"

CONTAINER="${MBC_PG_CONTAINER:-mbc360-postgres-dev}"
PGUSER_="${MBC_PG_USER:-mbc360}"
PGDB="${MBC_PG_DB:-mbc360}"
COMPOSE_FILE="docker-compose.dev.yml"
BACKUP_DIR="${TMPDIR:-/tmp}/mbc360-reset-$(date +%Y%m%d-%H%M%S)"

ASSUME_YES=false
KEEP_USERS=false
for arg in "$@"; do
  case "$arg" in
    --yes|-y) ASSUME_YES=true ;;
    --keep-users) KEEP_USERS=true ;;
    # Print the header comment block only — awk (not sed) because it must stop at
    # the first non-comment line, and BSD/macOS sed cannot express that portably.
    --help|-h) awk 'NR>1 && /^#/ { sub(/^# ?/, ""); print; next } NR>1 { exit }' "$0"; exit 0 ;;
    *) echo "Unknown option: $arg (try --help)" >&2; exit 2 ;;
  esac
done

say()  { printf '\n\033[1;34m==> %s\033[0m\n' "$1"; }
ok()   { printf '\033[0;32m    ✓ %s\033[0m\n' "$1"; }
warn() { printf '\033[0;33m    ! %s\033[0m\n' "$1"; }
die()  { printf '\n\033[0;31mFAILED: %s\033[0m\n' "$1" >&2; exit 1; }

# --------------------------------------------------------------------------
# Safety rail: this script destroys data, so refuse to run against anything
# that does not look like the local dev database.
# --------------------------------------------------------------------------
[ -f apps/api/.env ] || die "apps/api/.env not found — copy it from .env.example first"
DB_URL="$(grep -E '^DATABASE_URL=' apps/api/.env | head -1 | cut -d= -f2- | tr -d '"'"'"'')"
[ -n "$DB_URL" ] || die "DATABASE_URL is not set in apps/api/.env"
case "$DB_URL" in
  *@localhost:*|*@127.0.0.1:*) : ;;
  *) die "DATABASE_URL does not point at localhost — refusing to wipe a remote database.
       URL: $DB_URL
       This script is for the local dev database only. Never point it at production." ;;
esac

if ! $ASSUME_YES; then
  printf '\n\033[0;31mThis DELETES every row in the local dev database\033[0m (%s).\n' "$DB_URL"
  printf 'Preserved: Cosmetri access/refresh tokens%s.\n' "$($KEEP_USERS && echo ' and real SSO users')"
  printf 'Then it re-applies all migrations and re-seeds the standard dataset.\n\n'
  read -r -p 'Type "reset" to continue: ' answer
  [ "$answer" = "reset" ] || die "cancelled (nothing was changed)"
fi

# --------------------------------------------------------------------------
# 1. Postgres up
# --------------------------------------------------------------------------
say "Making sure the dev Postgres container is up"
docker compose -f "$COMPOSE_FILE" up -d >/dev/null
for _ in $(seq 1 30); do
  if docker exec "$CONTAINER" pg_isready -U "$PGUSER_" -d "$PGDB" >/dev/null 2>&1; then break; fi
  sleep 2
done
docker exec "$CONTAINER" pg_isready -U "$PGUSER_" -d "$PGDB" >/dev/null 2>&1 \
  || die "Postgres container '$CONTAINER' did not become ready"
ok "$CONTAINER ready"

psql_q() { docker exec "$CONTAINER" psql -U "$PGUSER_" -d "$PGDB" -tAc "$1"; }

# Row counts are only readable if the schema exists — a brand-new volume has
# none, in which case there is nothing to preserve and nothing to warn about.
table_exists() { [ "$(psql_q "SELECT to_regclass('public.$1') IS NOT NULL")" = "t" ]; }

# --------------------------------------------------------------------------
# 2. Preserve the Cosmetri tokens (and optionally real users)
# --------------------------------------------------------------------------
# The backup holds REAL tokens, so it must not be left lying in /tmp after a
# failure that never actually destroyed anything. If we die before the wipe, the
# database still has everything and the dump is redundant -> delete it. If we die
# AFTER the wipe, the dump may be the only copy left -> keep it and say where.
RESET_STARTED=false
cleanup_backup() {
  local code=$?
  if [ "$code" -ne 0 ] && ! $RESET_STARTED; then
    rm -rf "$BACKUP_DIR"
  elif [ "$code" -ne 0 ] && $RESET_STARTED; then
    printf '\033[0;33m    ! Database WAS reset. Your backup is at: %s\033[0m\n' "$BACKUP_DIR" >&2
  fi
}
trap cleanup_backup EXIT

say "Backing up what must survive the wipe"
mkdir -p "$BACKUP_DIR"
COSMETRI_ROWS=0
if table_exists cosmetri_connection; then
  COSMETRI_ROWS="$(psql_q 'SELECT count(*) FROM cosmetri_connection')"
fi
if [ "$COSMETRI_ROWS" -gt 0 ]; then
  # --column-inserts (not COPY) so the restore still works if a later migration
  # ADDS a nullable column to this table.
  docker exec "$CONTAINER" pg_dump -U "$PGUSER_" -d "$PGDB" \
    --data-only --column-inserts --table=public.cosmetri_connection \
    > "$BACKUP_DIR/cosmetri_connection.sql"
  ok "Cosmetri connection saved ($BACKUP_DIR/cosmetri_connection.sql)"
else
  warn "No Cosmetri connection stored — nothing to preserve (reconnect on the Integrations page afterwards)"
fi

USERS_BACKED_UP=false
if $KEEP_USERS && table_exists users; then
  REAL_USERS="$(psql_q "SELECT count(*) FROM users WHERE email NOT LIKE '%@demo.mbc360.local'")"
  if [ "$REAL_USERS" -gt 0 ]; then
    # Users only — NOT user_roles: role ids are regenerated by the seeder, so a
    # restored join row would point at a role that no longer exists. The roles
    # are reassigned below from the role KEY, which is stable.
    docker exec "$CONTAINER" psql -U "$PGUSER_" -d "$PGDB" -tAc \
      "COPY (SELECT u.email, u.oid, u.\"displayName\", d.name, u.active, r.key
             FROM users u
             LEFT JOIN departments d ON d.id = u.\"departmentId\"
             LEFT JOIN user_roles ur ON ur.\"userId\" = u.id
             LEFT JOIN roles r ON r.id = ur.\"roleId\"
             WHERE u.email NOT LIKE '%@demo.mbc360.local') TO STDOUT WITH (FORMAT csv)" \
      > "$BACKUP_DIR/real_users.csv"
    USERS_BACKED_UP=true
    ok "$REAL_USERS real SSO user(s) saved ($BACKUP_DIR/real_users.csv)"
  else
    warn "No real SSO users to keep"
  fi
fi

# --------------------------------------------------------------------------
# 3. Wipe + migrate + seed
# --------------------------------------------------------------------------
# `prisma migrate reset` drops the schema and re-applies every migration.
# Preferred over `docker compose down -v` because it leaves the container and
# its volume alone (no waiting for Postgres to boot, no network/volume churn).
#
# The seed is run as its OWN step on purpose: despite what the Prisma docs imply
# (and what the comment at the top of prisma/seed.ts used to claim), Prisma 7's
# `migrate reset` does NOT invoke the seed declared in prisma.config.ts — this
# script's own verification step is what caught that, having produced an empty
# database. Keeping it separate also means a seed failure reports as a seed
# failure rather than being buried in reset output.
say "Resetting the schema and re-applying migrations"
RESET_STARTED=true
npm run --silent db:reset -w @mbc360/api || die "prisma migrate reset failed"
ok "Schema reset, migrations applied"

say "Seeding the standard dataset"
npm run --silent db:seed -w @mbc360/api || die "seeding failed (the schema is reset but EMPTY — re-run this script)"
ok "Seed completed"

# --------------------------------------------------------------------------
# 4. Restore
# --------------------------------------------------------------------------
if [ "$COSMETRI_ROWS" -gt 0 ]; then
  say "Restoring the Cosmetri tokens"
  if docker exec -i "$CONTAINER" psql -U "$PGUSER_" -d "$PGDB" -v ON_ERROR_STOP=1 -q \
       < "$BACKUP_DIR/cosmetri_connection.sql" >/dev/null 2>&1 \
     && [ "$(psql_q 'SELECT count(*) FROM cosmetri_connection')" -gt 0 ]; then
    ok "Cosmetri connection restored — no need to re-paste tokens"
  else
    warn "Could not restore the Cosmetri connection automatically."
    warn "The dump is kept at: $BACKUP_DIR/cosmetri_connection.sql"
    warn "Restore it manually, or reconnect on the Integrations page."
  fi
fi

if $USERS_BACKED_UP; then
  say "Restoring real SSO users"
  restored=0
  while IFS=, read -r email oid display dept active rolekey; do
    [ -n "$email" ] || continue
    # Strip the quotes csv adds around values containing separators.
    unquote() { printf '%s' "$1" | sed 's/^"//; s/"$//; s/""/"/g'; }
    email="$(unquote "$email")"; display="$(unquote "$display")"
    dept="$(unquote "$dept")"; rolekey="$(unquote "$rolekey")"
    docker exec "$CONTAINER" psql -U "$PGUSER_" -d "$PGDB" -v ON_ERROR_STOP=1 -q -c "
      WITH dep AS (
        INSERT INTO departments (id, name)
        SELECT gen_random_uuid()::text, '$dept'
        WHERE '$dept' <> '' AND NOT EXISTS (SELECT 1 FROM departments WHERE name = '$dept')
        RETURNING id
      ), u AS (
        INSERT INTO users (id, email, oid, \"displayName\", \"departmentId\", active, \"createdAt\", \"updatedAt\")
        VALUES (
          gen_random_uuid()::text, '$email', $( [ -n "$oid" ] && echo "'$oid'" || echo NULL ),
          '$display', (SELECT id FROM departments WHERE name = '$dept'),
          $( [ "$active" = "t" ] && echo true || echo false ), now(), now()
        )
        ON CONFLICT (email) DO UPDATE SET \"displayName\" = EXCLUDED.\"displayName\"
        RETURNING id
      )
      INSERT INTO user_roles (\"userId\", \"roleId\")
      SELECT u.id, r.id FROM u, roles r WHERE r.key = '$rolekey'
      ON CONFLICT DO NOTHING;" >/dev/null 2>&1 && restored=$((restored + 1)) \
      || warn "could not restore $email"
  done < "$BACKUP_DIR/real_users.csv"
  ok "$restored real user(s) restored"
fi

# --------------------------------------------------------------------------
# 5. Report
# --------------------------------------------------------------------------
say "Result"
docker exec "$CONTAINER" psql -U "$PGUSER_" -d "$PGDB" -c "
SELECT 'projects'                     AS table, count(*) AS rows FROM projects
UNION ALL SELECT 'project_reviewers',  count(*) FROM project_reviewers
UNION ALL SELECT 'users',              count(*) FROM users
UNION ALL SELECT 'users without role', count(*) FROM users u
          LEFT JOIN user_roles ur ON ur.\"userId\" = u.id WHERE ur.\"userId\" IS NULL
UNION ALL SELECT 'roles',              count(*) FROM roles
UNION ALL SELECT 'cosmetri_connection',count(*) FROM cosmetri_connection
ORDER BY 1;"
psql_q 'SELECT id || '\''  ('\'' || "productCode" || '\'')'\'' FROM projects' | sed 's/^/    project: /'

# A "successful" run that left the database empty is a failure, not a result —
# fail loudly rather than printing a table of zeros and exiting 0.
[ "$(psql_q 'SELECT count(*) FROM projects')" -gt 0 ] || die "seed produced no project — the database is empty"
[ "$(psql_q 'SELECT count(*) FROM users')"    -gt 0 ] || die "seed produced no users — the database is empty"
NO_ROLE="$(psql_q 'SELECT count(*) FROM users u LEFT JOIN user_roles ur ON ur."userId" = u.id WHERE ur."userId" IS NULL')"
[ "$NO_ROLE" = "0" ] || warn "$NO_ROLE user(s) have no role assigned"

# The backup dir holds real tokens, so it is only kept when it is still the ONLY
# copy of something. Three cases: nothing was ever backed up (empty dir — drop it
# quietly), everything is back in the database (drop it), or a restore failed
# (keep it and say so loudly, since it may now be the only copy).
BACKED_UP_ANYTHING=false
[ "$COSMETRI_ROWS" -gt 0 ] && BACKED_UP_ANYTHING=true
$USERS_BACKED_UP && BACKED_UP_ANYTHING=true

if ! $BACKED_UP_ANYTHING; then
  rm -rf "$BACKUP_DIR"
elif [ "$COSMETRI_ROWS" -eq 0 ] || [ "$(psql_q 'SELECT count(*) FROM cosmetri_connection')" -gt 0 ]; then
  rm -rf "$BACKUP_DIR"
  ok "Backup no longer needed — removed"
else
  warn "Backup kept at $BACKUP_DIR (it contains real tokens — delete it once restored)"
fi

printf '\n\033[0;32mDone.\033[0m The dev database now holds the standard seeded dataset.\n'
printf 'If `npm run dev` was running, the API reconnects on its own.\n'
