// GENERATED by packages/shared/scripts/generate-column-reads.ts — do not edit by hand.
//
// For each gate, every register its readiness reads and, per register, the columns it
// reads (an empty list means only the rows themselves are read: "has at least one row").
// Measured by tracing the real checks over many random projects; see column-reads-lib.ts
// for why it is measured rather than written. `npm run verify:readiness` fails when this
// file no longer matches a fresh trace — regenerate with `npm run generate:column-reads`.
//
// REGISTER_READS_BY_GATE is what the gate's CHECKS read: it decides which gate owns a column.
// TRIGGER_READS_BY_GATE is what its TRIGGERS read to decide whether an item applies: those
// columns are part of what the gate's signature records, but a trigger never owns a column.
export const REGISTER_READS_BY_GATE: Record<string, Record<string, string[]>> = {
  SG02: {
    developmentBrief: ['briefLink', 'briefOwner', 'briefStatus'],
    needsResearchQuestions: [],
    needsSignOff: ['date', 'name'],
    vulnerableUserAssessment: ['additionalAssessments', 'responsibleReviewer', 'safetyPathway', 'vulnerableGroup'],
  },
  SG03: {
    claimEvidenceTraceability: ['approvedWording', 'claimCategory', 'claimId', 'claimRisk', 'claimSubjects', 'evidenceBasisRequired', 'libraryEntryId', 'preliminaryEvidenceRequirement', 'regulatoryReviewDate', 'regulatoryReviewEvidence', 'regulatoryReviewOutcome', 'regulatoryReviewRationale', 'regulatoryReviewer', 'reviewedWording', 'technicalReviewDate', 'technicalReviewEvidence', 'technicalReviewOutcome', 'technicalReviewRationale', 'technicalReviewer'],
    competitorLandscape: [],
    skuClaimsPifRegister: ['claimId', 'regulatoryReviewRequired'],
    targetProductProfile: ['target'],
  },
  SG04: {
    pbCautionLimits: ['evidenceLink', 'gate4Disposition', 'linkedNextActionId', 'productStatus', 'reviewDate', 'reviewRationale', 'reviewer', 'reviewerAssessment'],
    prohibitedIngredients: ['evidenceLink', 'gate4Disposition', 'linkedNextActionId', 'productStatus', 'reviewDate', 'reviewRationale', 'reviewer', 'reviewerAssessment'],
    supplierRmEvidence: ['allergenStatement', 'approvedForUse', 'evidenceStatus', 'impurities', 'inciName'],
  },
  SG05: {
    competitorLandscape: [],
    evidencePlanProspective: [],
    needsSignOff: ['date', 'name'],
    targetProductProfile: ['target'],
    targetProductSignOff: ['date', 'name'],
  },
  SG06: {
    packagingSpecsArtwork: ['artworkVersion', 'compatibilityEvidence', 'specLink', 'supplier'],
  },
  SG07: {
    criticalSafetyFindings: ['criticalFinding', 'evidenceLink', 'findingStatus', 'linkedNextActionId', 'safetyReviewerConclusion', 'severity'],
    formulationSafetyFinalSignOff: ['notes', 'safetyQuestion', 'status'],
    formulationSafetyMatrix: ['allergenIfra', 'exposureRationale', 'impurityProof', 'inciName', 'rmCode', 'safetyDecision'],
    generalRestrictedCaution: ['assessmentOutcome'],
    pbCautionLimits: ['gate4Disposition', 'productStatus'],
    prohibitedIngredients: ['gate4Disposition', 'productStatus'],
    supplierRmEvidence: ['approvedForUse', 'evidenceStatus', 'rmCode'],
  },
  SG08: {
    evidenceTestProtocol: ['acceptanceLimit', 'reportLink', 'testMethod'],
  },
  SG09: {
    stabilityRelease: ['acceptanceCriteria'],
  },
  SG10: {
    claimEvidenceTraceability: ['claimId', 'regulatoryReviewOutcome', 'status'],
    packagingSpecsArtwork: ['approval', 'claimIds', 'market'],
    pifChecklistAsean: ['status'],
    publishedInfoApproval: ['noProductClaim', 'noProductClaimConfirmedBy', 'workflowState'],
    regulatoryChecklistStatus: ['checklistLink', 'dossierType', 'market', 'owner', 'regulatoryApproval', 'status'],
    skuClaimsPifRegister: ['claimId', 'evidenceLink', 'market', 'pifLink'],
    supplierRmEvidence: ['approvedForUse', 'evidenceStatus', 'rmCode'],
  },
  SG11: {
    gmpLinks: ['link'],
    publishedInfoApproval: ['workflowState'],
    releasedLabelRegister: ['newArtworkFile', 'newLabelVersion'],
    stabilityRelease: ['releaseDecision'],
    supplierRmEvidence: ['approvedForUse', 'evidenceStatus', 'rmCode'],
  },
  SG12: {
    claimEvidenceTraceability: ['approvedWording', 'claimCategory', 'claimRisk', 'claimSubjects', 'reviewedWording'],
    vulnerableUserAssessment: ['vulnerableGroup'],
  },
};

export const TRIGGER_READS_BY_GATE: Record<string, Record<string, string[]>> = {
  SG03: {
    claimEvidenceTraceability: ['approvedWording', 'claimCategory', 'claimId', 'claimRisk', 'claimSubjects', 'libraryEntryId', 'reviewedWording'],
    skuClaimsPifRegister: ['claimId', 'regulatoryReviewRequired'],
  },
  SG04: {
    supplierRmEvidence: ['rmCode'],
  },
  SG08: {
    studyProtocolSetup: ['plannedValue'],
  },
  SG10: {
    claimEvidenceTraceability: ['claimCategory', 'evidenceBasisRequired'],
  },
  SG12: {
    claimEvidenceTraceability: ['approvedWording', 'claimCategory', 'claimRisk', 'claimSubjects', 'reviewedWording'],
    vulnerableUserAssessment: ['vulnerableGroup'],
  },
};

// The parts of a project other than registers (BOM, costing, assessments…) each gate's readiness reads.
export const PROJECT_SLICE_READS_BY_GATE: Record<string, string[]> = {
  SG01: ['identity'],
  SG02: ['assessments'],
  SG03: ['assessments'],
  SG04: ['assessments', 'bom'],
  SG05: ['assessments', 'bom', 'costing', 'formulaProperties'],
  SG06: ['assessments', 'marketTracks'],
  SG07: ['assessments', 'bom'],
  SG08: ['assessments', 'studyApprovals'],
  SG09: ['assessments', 'formulaProperties', 'formulaVersionHistory'],
  SG10: ['assessments', 'bom', 'identity', 'marketTracks'],
  SG11: ['bom', 'changes', 'identity', 'marketTracks'],
  SG12: ['assessments', 'changes', 'identity', 'marketTracks', 'postLaunchReviews'],
};
